#pragma once

#include <cstdint>
#include <cstdlib>
#include <array>
#include <vector>
#include <span>
#include <string>
#include <string_view>
#include <algorithm>
#include <istream>
#include <ostream>
#include <fstream>
#include <filesystem>
#include <optional>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <bit>
